##maf version=1 scoring=zero
a score=0.000000
s hg19 0 0 + 0 TACCGTCCGGACCTAGGGCTTCCA
s panTro4 0 0 + 0 TACCGTCCGGACCTAGGGCTACCA
s gorGor3 0 0 + 0 TACCGTCTGGACCTAGGGCTTCCA
s ponAbe2 0 0 + 0 ------------------------
s nomLeu3 0 0 + 0 -ACCGCCCGGACCTAGGGCTCCCA
s rheMac3 0 0 + 0 ------------------------
s macFas5 0 0 + 0 ------------------------
s papHam1 0 0 + 0 ------------------------
s chlSab1 0 0 + 0 ------------------------
s calJac3 0 0 + 0 TACCGTCTGGACCTAGG-CCTCCA
s saiBol1 0 0 + 0 ------------------------
s otoGar3 0 0 + 0 AACTATCCGC-CTTAAGGCTTCCA
s tupChi1 0 0 + 0 TACCG-GCGGGCCTAGGGCCGC--
s speTri2 0 0 + 0 TGCCGTACGGGCCTAAGGCCTTCA
s jacJac1 0 0 + 0 ------------------------
s micOch1 0 0 + 0 ------------------------
s criGri1 0 0 + 0 ---CGTACGGACCTAAGG-CTGCA
s mesAur1 0 0 + 0 ------------------------
s hetGla2 0 0 + 0 TGCCGTACTGGCTTTGGGCCTCCA
s cavPor3 0 0 + 0 ------------------------
s chiLan1 0 0 + 0 TGCTGTACGCGCTTTGGGCCTCCA
s octDeg1 0 0 + 0 ----GTACAGGCT-TGAGCCTCAA
s oryCun2 0 0 + 0 ------------------------
s ochPri3 0 0 + 0 ------------------------
s susScr3 0 0 + 0 ATC-ATACGCGCCTGGGGTCCCCG
s vicPac2 0 0 + 0 TCC-GTGCGCGCCTAGGGCCCCCA
s camFer1 0 0 + 0 TTC-GTGCGCGCCTAGGGCCCCCA
s turTru2 0 0 + 0 ------------------------
s orcOrc1 0 0 + 0 TTCCGTGCGCGCCTAGGGTCCCCA
s panHod1 0 0 + 0 TTG-GTGCGCGCCTAGGGTGTCC-
s bosTau7 0 0 + 0 TCGCGTGCGCGCC---GG-ATCC-
s oviAri3 0 0 + 0 TTGCATGCGCGCCTAGGGTGTCC-
s capHir1 0 0 + 0 TTGCGTGCGCGCCTAGGGTGTCC-
s equCab2 0 0 + 0 TTCCGCACGTGCCTAAGGCTTCC-
s cerSim1 0 0 + 0 TTCCGCCCGTGCCTAAGGCCTCCA
s felCat5 0 0 + 0 TTCTCTACATACCTAAGGCTTCCA
s canFam3 0 0 + 0 TTCC-TGCGCACCTGAGGTCAC-A
s musFur1 0 0 + 0 TTCC-TGCGTACCAAGGGCCACCC
s ailMel1 0 0 + 0 CCCCTTGCGTACCTAAGGCCACCA
s odoRosDiv1 0 0 + 0 TCCCCTGGGCACCTAGGGCCACCA
s pteAle1 0 0 + 0 TTCTATACGTGCCCACGGACTCCA
s pteVam1 0 0 + 0 ------------------------
s myoDav1 0 0 + 0 TTGCGTACGTGCCTACAGCCTCCG
s myoLuc2 0 0 + 0 TCGCGTACGTGCCTACAGCCTCCG
s eptFus1 0 0 + 0 TCGCGTACGTGCCTACAGCCTCCG
s sorAra2 0 0 + 0 ------------------------
s conCri1 0 0 + 0 CCCCG--CGTGCCTAAGGCCTCCA
s loxAfr3 0 0 + 0 TACGGTACGCGCTTGGGGCCTCTA
s eleEdw1 0 0 + 0 TGCGGTACGCGTCTAGAACCCC-A
s triMan1 0 0 + 0 TGCGGTACGCGCTTAGGGCCTCTA
s chrAsi1 0 0 + 0 TACAATACTCGTTTAGGGCCTCCA
s echTel2 0 0 + 0 GGCAACACGCGCCTGAGGCCACCA
s oryAfe1 0 0 + 0 TACAGTACGCGCTTAGGGCCTCTA
s dasNov3 0 0 + 0 CTCGGTGCGCGCCTAGGGCCTCCT
s monDom5 0 0 + 0 TAG-CTG-GTGCCCGAGGACA---
s sarHar1 0 0 + 0 TAG-----GTGCCCGGGGATTCT-
s macEug2 0 0 + 0 ------------------------
s ornAna1 0 0 + 0 ------------------------
s falChe1 0 0 + 0 CGACG-TCGTGATTACAGT-----
s falPer1 0 0 + 0 CGACG-TCGTGATTACAGT-----
s ficAlb2 0 0 + 0 CGA---TCGTGATTACAGTAGC--
s zonAlb1 0 0 + 0 TGA-G-TCGTGATTAGAGCAGC--
s geoFor1 0 0 + 0 TGAC--TCGAGATTACAGTAGC--
s taeGut2 0 0 + 0 CGA-G-TCGTGATAACAGTCG---
s pseHum1 0 0 + 0 CGA-G-TCGTGATTACAGTAGC--
s melUnd1 0 0 + 0 TGAC--TCGTGATTACAGT-----
s amaVit1 0 0 + 0 CGAC--TCGTGAATACAGTAG---
s araMac1 0 0 + 0 ------------------------
s colLiv1 0 0 + 0 AGCCG-TCGTGATTACAGTAG---
s anaPla1 0 0 + 0 TGAC--TCGTGATTATAGTAG---
s galGal4 0 0 + 0 GGAC--TCGTGATTCTAGTAG---
s melGal1 0 0 + 0 GGAC--TCGTGATTATAGT-----
s allMis1 0 0 + 0 TGA-T-TCGTGCGTATAGTCG---
s cheMyd1 0 0 + 0 TGACT-TCCTGCTCACAGCAGCC-
s chrPic1 0 0 + 0 TGACT-TCCCGCTCACAGCAGCC-
s pelSin1 0 0 + 0 TGA----CTTGCTCACAGCAG---
s apaSpi1 0 0 + 0 TGA----CTTGCTCACAGCAG---
s anoCar2 0 0 + 0 TGACT-TCGCGCCTATACAAGCC-
s xenTro7 0 0 + 0 ----TTCCTGGAGCATGGCCTC-G
s latCha1 0 0 + 0 ------------------------
s tetNig2 0 0 + 0 GGC---------------------
s fr3 0 0 + 0 CGC---------------------
s takFla1 0 0 + 0 CGC---------------------
s oreNil2 0 0 + 0 CGC----CAGGACCAGGGACGCT-
s neoBri1 0 0 + 0 CGC----CAGGACCAGGGACG---
s hapBur1 0 0 + 0 CGC----CAGGACCAGGGACGC--
s mayZeb1 0 0 + 0 CGC----CAGGACCAGGGACG---
s punNye1 0 0 + 0 CGC----CAGGACCAGGGACGC--
s oryLat2 0 0 + 0 TGC----CGATAACAGGGGCG---
s xipMac1 0 0 + 0 TGC----CGGTCGTAGGGGCGCC-
s gasAcu1 0 0 + 0 AGCCG-TCGGGAGCGGGGCCGCGA
s gadMor1 0 0 + 0 ---TG-TCGGGTGTATGGTTGCC-
s danRer7 0 0 + 0 TGC----CTTAAGAAGGGCCG-C-
s astMex1 0 0 + 0 TGC---------------------
s lepOcu1 0 0 + 0 ACCCT-CCTAAAATATGGCCG---
s petMar2 0 0 + 0 ------------------------
